name: Continuous Integration

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Deps
        run: pip install -r requirements/base.txt
      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          DJANGO_SETTINGS_MODULE: config.settings.dev
        run: python app/manage.py test